#!/bin/sh
# Should check for Python executable name
if python3 -V
then
    PYTHON=python3
elif python -V
then
    PYTHON=python
else
    echo Could not find Python executable
    exit
fi
# Assume that we're starting in the resting directory, should check for this
APP_NAME=`$PYTHON -c "import project;print(project.app_name)"`
cd ..
TOP=`pwd`
# To provide website documentation create a working directory for Sphinx in the project directory
cd $TOP/webserver
mkdir doc
cd doc
# Create skeleton Sphinx files for website documentation
sphinx-quickstart -q -p $APP_NAME -a 'Generated by RESTInG' -v ''
echo -e "import os\nimport sys\nsys.path.append(os.path.abspath('../../resting'))\nextensions.append('sphinx.ext.autodoc')" >> conf.py
# Generate the Django site files
cd $TOP/resting
$PYTHON generate_rest_site.py
# Create static directory for the app
cd $TOP/webserver/website/$APP_NAME
mkdir static
cd static
mkdir $APP_NAME

# Create static subdirectory for hosting Sphinx-generated documentation
cd $APP_NAME
mkdir doc

# Create static directory for hosting downloads
mkdir downloads

# Copy the REST client Python module to the downloads folder
cp $TOP/resting/rest_client.py downloads
